stages:
  - test
  - deploy

opentelemetry-dev-2-vm-1:
  trigger:
    include:
      - local: deployments/dev-2-vm-1/.gitlab-ci.yml
    strategy: mirror
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - 'deployments/dev-2-vm-1/**/*'
    - when: manual