stages:
  - test
  - config
  - deploy

include:
  - component: $CI_SERVER_FQDN/components/docker/config-docker@~latest
    inputs:
      as: "docker-lint"
      local_path: "deployments/dev-2-vm-1"
  - component: $CI_SERVER_FQDN/components/docker/config-dir-copy-nr@~latest
    inputs:
      as: "dev-2-vm-1-config"
      config_path: "deployments/dev-2-vm-1/config"
      remote_host: "dev-2-vm.margusm.dev"
      remote_user: "margus"
      remote_config_path: "deployments/opentelemetry-dev-2-vm-1/config"
  - component: $CI_SERVER_FQDN/components/docker/deploy-nr@~latest
    inputs:
      as: "dev-2-vm-1-deploy"
      local_path: "deployments/dev-2-vm-1"
      remote_host: "dev-2-vm.margusm.dev"
      remote_user: "margus"
      remote_path: "deployments/opentelemetry-dev-2-vm-1"


